### PR TITLE
feat: updating `cargo.toml` and `package.json` before version commit

### LINKED ISSUE #28: Automatically bump `cargo.toml` version to match `package.json`.
### Specification

We need the `cargo.toml` version to match the `package.json` version for the CI release/prerelease jobs to work. This needs to happen between the `npm version` command bumping the version number and it committing the tag. There is a `version` script in the `package.json` that is run at that stage.

We need to create a script that will update the `cargo.toml` version to match the new version and make sure it is included in the version commit. 

### Additional context

* Related #1 

### Tasks

1. create a `version` script to update the `cargo.toml` version.
2. Make sure it's included within the version commit.
3. Make sure that the pre-release and release CI jobs are passing and the package is being published.

### PR DESCRIPTION
**Pull request by tegefaulkes**
### Description

This PR adds a `version` script that updates the `cargo.toml` version to match the new `package.json` version when a `npm version` is run.

It also rolls the `postVersion` script into the `version` script. The changes from the `postVersion` script were not included in the tagged version commit.  

* Related #28

### Issues Fixed

* Fixes #28 

### Tasks
* [x] 1. Ensure that automatic changes to the version numbers in the `package.json` dependencies and `cargo.toml` file are updated with the new version from the `npm version` command. ensure that these changes are included in the tagged version commit.
* [x] 2. Ensure that there are no un-staged or un-commited changes that should be included in the commit.
* [x] 3. Verify this all works with a pre-release version.

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by tegefaulkes** [comment]
Do we want to add anything else while we're here? Such as some checks in the `preVersion` stage? Such as a lint, build and test check?

**Comment by tegefaulkes** [comment]
Ah, the cargo lock file isn't being updated, we want to commit changes to that as well.

**Comment by tegefaulkes** [comment]
That should fix it. Running `npm install` and `npm run build` shouldn't result in updates to any lock files. Except for the optional dependencies, these will change based off of platform and availability.

**Comment by tegefaulkes** [comment]
I think the only thing left is to merge and run a test job to see if it publishes.

**Comment by CMCDragonkai** [comment]
Is this going to be merged?

**Pull request merged**
