### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1165609820 for 63e7c4130a41ec90d477f7483ef4fa615790ea8e

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1165609820

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1165628220 for 1f6fc4b291542dc761b980d40da96a897c195aad

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1165628220

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1165628220 for 1f6fc4b291542dc761b980d40da96a897c195aad

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1165628220

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1165663976 for 31df5936ca7c4e6a266fecf6559d03c75db443d0

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1165663976

**Comment by tegefaulkes** [comment]
Looks like my recent merge has problems with platform specific CI tests. I'll have to revert it and do more extensive testing.

**Comment by CMCDragonkai** [comment]
Can you be more precise? What are the failures? @brynblack we will need those 2 machines up to help run interactive debugging for this - when the new machine arrives next week.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1165722518 for e8b1d8a6d4f05a9efebf2b4947108f7bf7aacecd

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1165722518

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1165722518 for e8b1d8a6d4f05a9efebf2b4947108f7bf7aacecd

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1165722518

**Pull request merged**
