### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1212829103 for 2ac6b4d13b6555ffe17319cac275e5f28949ab86

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1212829103

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1212829103 for 2ac6b4d13b6555ffe17319cac275e5f28949ab86

https://gitlab.com/MatrixAI/open-source/js-quic/-/pipelines/1212829103

**Comment by CMCDragonkai** [comment]
Hey why are there wip commits going to staging?

14 Mar 2024 00:20:18 Matrix AI Bot ***@***.***>:

**Comment by tegefaulkes** [comment]
It was a mistake on my part. I reverted it immediately.

**Pull request merged**
